Add example for AWS Lambda & Serverless Framework
getsentry/examples pull request #101
Opened 2021-07-23 22:46 UTC by connorads

This is to add a examples of integrating Sentry with [AWS Lambda in Node and Python with Lambda Layers using Serverless Framework](https://sentry-docs-git-fork-connorads-patch-1.sentry.dev/product/integrations/cloud-monitoring/aws-lambda/#serverless-framework).

Follow up from https://github.com/getsentry/sentry-docs/pull/3830

Wasn't really sure how much detail to add with the README/docs and wasn't sure about the folder structure.
Feedback and changes welcome 🤗

## Testing

### Node

![image](https://user-images.githubusercontent.com/10026538/126847973-df40c32f-4a3b-4507-bf3c-fcf0c32dc1f7.png)

### Python

![image](https://user-images.githubusercontent.com/10026538/126847917-ace1d441-fa3b-4409-80c7-0fd71d63560f.png)

### Sentry

![image](https://user-images.githubusercontent.com/10026538/126847870-01153034-af00-44a1-a314-04e9bdcb9923.png)

2021-07-26 12:17 UTC, kamilogorek approved these changes
LGTM! Feel free to merge it @ahmedetefy if you also +1

2021-07-26 12:50 UTC, ahmedetefy commented
Hey @connorads 

Thanks for opening the PR. The Serverless examples look good

However, rather than changing the directory stucture, I think it makes more sense to just add a `serverless-framework` dir to this path for Node `aws-lambda/node` that contains your serverless example 
and well the same for Python as well!

2021-07-26 12:52 UTC, ahmedetefy requested changes
Hey @connorads 

Thanks for opening the PR. The Serverless examples look good

However, rather than changing the directory stucture, I think it makes more sense to just add a `serverless-framework` directory to the following path `aws-lambda/node` for Node that contains your Serverless example, and well the same for Python as well!

2021-07-30 19:23 UTC, connorads commented
Hey @ahmedetefy, let me know what you think of the new structure

2021-08-09 22:26 UTC, connorads commented
Hey @ahmedetefy, we good to merge this now?

2021-08-12 13:22 UTC, connorads commented on aws-lambda/node/serverless-framework/serverless.yml
> +    - arn:aws:lambda:${self:provider.region}:943013980633:layer:SentryNodeServerlessSDK:latest
Oops, note to self: Need to change this back to remove the `latest` stuff - this was some testing for https://github.com/getsentry/sentry-javascript/issues/3834 that slipped in here when doing the folder moves 😬

2021-08-12 14:40 UTC, connorads commented on aws-lambda/node/serverless-framework/serverless.yml
> +    - arn:aws:lambda:${self:provider.region}:943013980633:layer:SentryNodeServerlessSDK:latest
Fixed in https://github.com/getsentry/examples/pull/101/commits/cbc427cd781e65b7eb436b9bd54ddf49f6b9703d

2021-08-17 08:47 UTC, merged

2021-08-17 08:47 UTC, kamilogorek commented
Thanks!